source 'https://rubygems.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.0.2'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'

# Use CoffeeScript for .js.coffee assets and views
gem 'coffee-rails', '4.0.1'

# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem 'therubyracer', '0.12.0', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails', '3.0.4'

# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
#gem 'turbolinks'

# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '1.0.2'

group :doc do
  # bundle exec rake doc:rails generates the API under doc/api.
  gem 'sdoc', require: false
end

# Use ActiveModel has_secure_password
# gem 'bcrypt-ruby', '~> 3.0.0'

# Use unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano', group: :development

# Use debugger
# gem 'debugger', group: [:development, :test]

gem 'pg', '0.17.1'
gem 'acts_as_tree', '1.5.0'
gem 'acts_as_list', '0.3.0'
gem 'rails_config', '0.3.3'
gem 'kaminari', '0.15.0'
gem 'rqrcode', '0.4.2'
gem 'rqrcode_png', '0.1.2'
gem 'bartt-ssl_requirement', '1.4.2'
gem 'mail-iso-2022-jp', '2.0.2'
gem 'iconv', '1.0.4'
gem 'jpmobile', '4.0.0'
gem 'activerecord-session_store', '0.1.0', github: 'rails/activerecord-session_store'
gem 'rmagick', '2.13.2'
gem 'activerecord-import', '0.5.0'
gem 'paperclip', '3.5.2'

# assets
gem 'jquery-ui-rails', '4.1.1'
gem 'less-rails', '2.4.2'
gem 'twitter-bootstrap-rails', '2.2.8'
gem 'ckeditor', '4.0.8'
gem 'prototype-rails', '4.0.0', git: 'git://github.com/rails/prototype-rails'
gem 'prototype_legacy_helper', '0.0.0', git: 'git://github.com/rails/prototype_legacy_helper.git'

# for development
group :development do
  gem 'quiet_assets', '1.0.2'
end

# for development, test
group :development, :test do
  gem 'rspec-rails', '2.14.1'
  gem 'shoulda-matchers', '2.4.0'
  gem 'factory_girl_rails', '4.3.0'
  gem 'database_cleaner', '1.2.0'
  gem 'capybara', '2.2.1'
  gem 'timecop', '0.7.1'
end

# for cron
gem 'whenever', :require => false

# for Engine
gem 'advertisement_management', path: 'vendor/engines/advertisement_management'
gem 'blog_management', path: 'vendor/engines/blog_management'
#gem 'browsing_support', path: 'vendor/engines/browsing_support'
gem 'consult_management', path: 'vendor/engines/consult_management'
gem 'event_calendar', path: 'vendor/engines/event_calendar'
gem 'import_page', path: 'vendor/engines/import_page'
gem 'lost_link_check', path: 'vendor/engines/lost_link_check'
gem 'section_info_configure', path: 'vendor/engines/section_info_configure'
gem 'site_design', path: 'vendor/engines/site_design'
